on:
  workflow_dispatch:
name: Test File
jobs:
  file1:
    name: Test chromium dev nosync
    runs-on: ubuntu-latest
    steps:
    - name: Download & Extract Files 64 bit
      run: |
        oldURL1="https://github.com/macchrome/chromium/releases/download/v86.0.4185.0-r769185-Win64/Chrome-bin.7z"
        newURL1="https://github.com/RobRich999/Chromium_Clang/releases/download/v99.0.4800.0-r954746-win64-sse3/chrome.zip"
        oldFile1=${oldURL1##*/}
        newFile1=${newURL1##*/}
        aria2c $oldURL1
        aria2c $newURL1
        7z x $oldFile1 -o64bit/old
        7z x $newFile1 -o64bit/new
    - name: List Files 64 bit
      run: |
        cd 64bit
        ls -R
        cd ..
    - name: Download & Extract Files 32 bit
      run: |
        oldURL2="https://github.com/macchrome/chromium/releases/download/v86.0.4185.0-r769185-Win64/Chrome-bin.7z"
        newURL2="https://github.com/RobRich999/Chromium_Clang/releases/download/v99.0.4778.0-r952844-win32-sse3/chrome.zip"
        oldFile2=${oldURL2##*/}
        newFile2=${newURL2##*/}
        aria2c $oldURL2
        aria2c $newURL2
        7z x $oldFile2 -o32bit/old
        7z x $newFile2 -o32bit/new
    - name: List Files 32 bit
      run: |
        cd 32bit
        ls -R
