on:
  workflow_dispatch:
name: Test File
jobs:
  file1:
    name: Test dbvis
    runs-on: ubuntu-latest
    steps:
    - name: Download & Extract Files 64 bit
      run: |
        oldURL1="https://www.dbvis.com/product_download/dbvis-11.0.5/media/dbvis_windows-x64_11_0_5.zip"
        newURL1="https://dbvis.com/product_download/dbvis-12.1.5/media/dbvis_windows-x64_12_1_5.zip"
        oldFile1=${oldURL1##*/}
        newFile1=${newURL1##*/}
        aria2c $oldURL1
        aria2c $newURL1
        7z x $oldFile1 -o${oldFile1}
        7z x $newFile1 -o${newFile1}
    - name: List Files 64 bit
      run: ls -R
    - name: Download & Extract Files 32 bit
      run: |
        oldURL2="https://www.dbvis.com/product_download/dbvis-11.0.5/media/dbvis_windows-x64_11_0_5.zip"
        newURL2="https://dbvis.com/product_download/dbvis-12.1.5/media/dbvis_windows-x64_12_1_5.zip"
        oldFile2=${oldURL2##*/}
        newFile2=${newURL2##*/}
        aria2c $oldURL2
        aria2c $newURL2
        7z x $oldFile2 -o${oldFile2}
        7z x $newFile2 -o${newFile2}
    - name: List Files 32 bit
      run: ls -R
