on:
  workflow_dispatch:
name: Test File
jobs:
  file1:
    name: Test File
    runs-on: windows-latest
    steps:
    - name: Test File
      run: |
        aria2c https://github.com/CCExtractor/ccextractor/releases/download/v0.94/CCExtractor_win_portable.zip
        7z x ./CCExtractor_win_portable.zip -oextracted
        cd extracted
        ls
      
