on:
  workflow_dispatch:
name: Test File
jobs:
  file1:
    name: Test File
    runs-on: ubuntu-latest
    steps:
    - name: Download & Extract
      run: |
        oldURL="https://github.com/hluk/CopyQ/releases/download/v5.0.0/copyq-v5.0.0.zip"
        newURL="https://github.com/hluk/CopyQ/releases/download/v6.0.1/copyq-6.0.1.zip"
        oldFile=${oldURL##*/}
        newFile=${newURL##*/}
        aria2c $oldURL
        aria2c $newURL
        7z x $oldFile -oold
        7z x $newFile -onew
    - name: List Files
      run: ls -R
