on:
  workflow_dispatch:
name: Test File
jobs:
  file1:
    name: Test chezmoi
    runs-on: ubuntu-latest
    steps:
    - name: Download & Extract Files 64 bit
      run: |
        oldURL1="https://github.com/twpayne/chezmoi/releases/download/v2.9.5/chezmoi_2.9.5_windows_amd64.zip"
        newURL1="https://github.com/twpayne/chezmoi/releases/download/v2.10.0/chezmoi_2.10.0_windows_amd64.zip"
        oldFile1=${oldURL1##*/}
        newFile1=${newURL1##*/}
        aria2c $oldURL1
        aria2c $newURL1
        7z x $oldFile1 -o64bit/old
        7z x $newFile1 -o64bit/new
    - name: List Files 64 bit
      run: |
        cd 64bit
        ls -R
        cd ..
    - name: Download & Extract Files 32 bit
      run: |
        oldURL2="https://github.com/twpayne/chezmoi/releases/download/v2.9.5/chezmoi_2.9.5_windows_amd64.zip"
        newURL2="https://github.com/twpayne/chezmoi/releases/download/v2.10.0/chezmoi_2.10.0_windows_i386.zip"
        oldFile2=${oldURL2##*/}
        newFile2=${newURL2##*/}
        aria2c $oldURL2
        aria2c $newURL2
        7z x $oldFile2 -o32bit/old
        7z x $newFile2 -o32bit/new
    - name: List Files 32 bit
      run: |
        cd 32bit
        ls -R
