on:
  workflow_dispatch:
name: Test File
jobs:
  file1:
    name: Test File
    runs-on: ubuntu-latest
    steps:
    - name: Test File
      run: |
        oldURL="https://github.com/CCExtractor/ccextractor/releases/download/v0.88/ccextractor.0.88-windows.binaries.zip"
        newURL="https://github.com/CCExtractor/ccextractor/releases/download/v0.94/CCExtractor_win_portable.zip"
        oldFile=${oldURL##*/}
        newFile=${newURL##*/}
        aria2c $oldURL
        aria2c $newURL
        7z x $oldFile -oold
        7z x $newFile -onew
        ls -R
      
